# Generated by Django 4.2.1 on 2023-07-07 09:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 7, 7, 9, 48, 4, 192379, tzinfo=datetime.timezone.utc))])),
                ('citizen_id', models.CharField(max_length=12, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('school_year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1950)])),
                ('current_tuition_debt', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
