# Generated by Django 4.2.1 on 2023-07-09 13:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dob_alter_user_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 7, 9, 13, 52, 24, 433274, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
