# Generated by Django 4.2.1 on 2023-07-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuition_collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionDebt',
            fields=[
                ('tuition_debt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ammount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuition_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuition_collection.tuitioncollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
