# Generated by Django 4.2.1 on 2023-07-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_debt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitiondebt',
            old_name='ammount',
            new_name='amount',
        ),
    ]
