# Generated by Django 4.2.1 on 2023-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionCollection',
            fields=[
                ('tuition_collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('semester', models.CharField(choices=[('1', 'Kỳ 1'), ('2', 'Kỳ 2'), ('3', 'Kỳ hè')], max_length=1)),
                ('school_year', models.PositiveSmallIntegerField()),
                ('tuition_collection_start', models.DateTimeField()),
                ('tuition_collection_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
