# Generated by Django 4.2.1 on 2023-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitioncollection',
            name='credit_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
